# Generated by Django 5.2.13 on 2026-04-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('weight_location', models.CharField(max_length=10)),
                ('context_trigger', models.CharField(max_length=10)),
                ('checkin_response', models.TextField()),
                ('follow_up_question', models.TextField(blank=True, null=True)),
                ('follow_up_response', models.TextField(blank=True, null=True)),
                ('llm_flag', models.CharField(max_length=20)),
                ('reflection', models.TextField()),
                ('intervention_type', models.CharField(max_length=20)),
                ('session_insight', models.TextField(blank=True, null=True)),
                ('prescription_quote', models.TextField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
