import { useState } from 'react';
import type { StressAnalysis, InterventionType, VitalSigns } from '../types';
import './PrescriptionCard.css';

const INTERVENTION_NAMES: Record<InterventionType, string> = {
  breathing: 'Box Breathing Reset',
  grounding: 'Grounding Exercise',
  movement: 'Movement Reset',
  reframe: 'Cognitive Reframe',
  journaling: 'Processing Prompt',
  rehearsal: 'Mental Rehearsal',
};

const INTERVENTION_DURATIONS: Record<InterventionType, string> = {
  breathing: '~1 minute',
  grounding: '~2 minutes',
  movement: '~90 seconds',
  reframe: '~3 minutes',
  journaling: '~5 minutes',
  rehearsal: '~3 minutes',
};

interface PrescriptionCardProps {
  analysis: StressAnalysis;
  chosenIntervention: InterventionType;
  vitals: VitalSigns | null;
  sessionInsight?: string;
  onRestart: () => void;
}

export default function PrescriptionCard({
  analysis,
  chosenIntervention,
  vitals,
  sessionInsight,
  onRestart,
}: PrescriptionCardProps) {
  const [cardId] = useState(() => Math.random().toString(36).substring(2, 8).toUpperCase());

  const generateRoutingReason = (): string => {
    if (!vitals) return 'Based on your session.';

    const weightLabel =
      vitals.weightLocation === 'head'
        ? 'where your mind was'
        : vitals.weightLocation === 'body'
          ? 'how your body was feeling'
          : 'what you were experiencing';

    const interventionName = INTERVENTION_NAMES[chosenIntervention];
    return `Based on ${weightLabel}, ${interventionName} was the right reset for this moment.`;
  };

  const handleCopy = async () => {
    const text = `🌿 My Stress Snapshot\n\n"${analysis.prescriptionQuote}"\n— from your session today\n\nIntervention: ${INTERVENTION_NAMES[chosenIntervention]}\n\n💡 Tip: ${analysis.tip}\n\n— Generated by Ori · WONE`;

    try {
      await navigator.clipboard.writeText(text);
      const btn = document.getElementById('copy-card');
      if (btn) {
        btn.textContent = '✓ Copied!';
        setTimeout(() => {
          btn.textContent = 'Copy to Clipboard';
        }, 2000);
      }
    } catch {
      console.log('Clipboard not available');
    }
  };

  const getInterventionIcon = (intervention: InterventionType): string => {
    const icons: Record<InterventionType, string> = {
      breathing: '🌬',
      grounding: '🫂',
      movement: '🔄',
      reframe: '✨',
      journaling: '📝',
      rehearsal: '🎯',
    };
    return icons[intervention];
  };

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
  });

  return (
    <div className="prescription-container step-container">
      <div className="prescription-header slide-up">
        <span className="label">Your Resilience Prescription</span>
        <p className="body-small">{dateStr} · {timeStr}</p>
      </div>

      {/* ─── The Card ─── */}
      <div className="prescription-card slide-up-delay-1" id="prescription-card">
        <div className="prescription-card-bg" />

        <div className="prescription-card-content">
          {/* Quote Section */}
          <div className="prescription-section prescription-quote-section">
            <div className="prescription-quote-block">
              <span className="prescription-quote-decoration">"</span>
              <blockquote className="prescription-quote-text">
                {analysis.prescriptionQuote}
              </blockquote>
            </div>
            <span className="prescription-quote-attribution">— from your session today</span>
          </div>

          {sessionInsight && (
            <>
              <div className="prescription-divider" />
              <div className="prescription-section prescription-insight">
                <span className="prescription-section-label">Ori's Reflection</span>
                <p className="prescription-insight-text">{sessionInsight}</p>
              </div>
            </>
          )}

          <div className="prescription-divider" />

          {/* Reset Completed Section */}
          <div className="prescription-section prescription-intervention">
            <span className="prescription-section-label">Reset Completed</span>
            <div className="prescription-intervention-row">
              <div className="prescription-intervention-icon">
                <span className="intervention-emoji">{getInterventionIcon(chosenIntervention)}</span>
              </div>
              <div>
                <p className="prescription-intervention-name">
                  {INTERVENTION_NAMES[chosenIntervention]}
                </p>
                <p className="body-small">{INTERVENTION_DURATIONS[chosenIntervention]}</p>
              </div>
            </div>
          </div>

          <div className="prescription-divider" />

          {/* Why This Reset Section */}
          <div className="prescription-section prescription-why">
            <span className="prescription-section-label">Why this reset</span>
            <p className="prescription-why-text">{generateRoutingReason()}</p>
          </div>

          <div className="prescription-divider" />

          {/* Tip Section */}
          <div className="prescription-section prescription-tip">
            <span className="prescription-section-label">Carry-Forward Tip</span>
            <div className="prescription-tip-content">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{ flexShrink: 0, marginTop: '2px' }}>
                <path d="M9 18h6M12 2v1M4.22 4.22l.71.71M1 12h1M4.22 19.78l.71-.71M20.49 4.93l-.71.71M23 12h-1M20.49 19.07l-.71-.71" />
                <circle cx="12" cy="12" r="5" />
              </svg>
              <p className="prescription-tip-text">{analysis.tip}</p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="prescription-card-footer">
          <div className="prescription-brand">
            <div className="prescription-brand-orb" />
            <span>Ori · WONE</span>
          </div>
          <span className="prescription-card-id">
            #{cardId}
          </span>
        </div>
      </div>

      {/* ─── Actions ─── */}
      <div className="prescription-actions slide-up-delay-3">
        <button className="btn-secondary" onClick={handleCopy} id="copy-card">
          Copy to Clipboard
        </button>
        <button className="btn-primary" onClick={onRestart} id="restart-flow">
          Start a New Check-in
          <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <path d="M1 4v5h5M15 12V7h-5" />
            <path d="M13.5 5.5A6.5 6.5 0 0 0 3 4L1 6M2.5 10.5A6.5 6.5 0 0 0 13 12l2-2" />
          </svg>
        </button>
      </div>

      <p className="prescription-disclaimer body-small slide-up-delay-4">
        This is a wellbeing check-in, not a clinical assessment.
        If you're experiencing persistent distress, please reach out to a qualified professional.
      </p>
    </div>
  );
}
